[workspace]
resolver = "2"
members = ["gateway", "core", "udfs"]
default-members = ["gateway", "udfs"]

[workspace.dependencies]
async-openai = { version = "0.27.2", package = "async-openai-compat" }
thiserror = "1.0.59"
