[workspace]
resolver = "2"
members = ["gateway", "core", "udfs", "guardrails"]
default-members = ["gateway", "udfs"]

[workspace.dependencies]
async-openai = { version = "0.27.2", package = "async-openai-compat" }
thiserror = "2.0.11"
