name: Build AI Gateway

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: main
  cancel-in-progress: true
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  build-linux:
    name: Build for Linux
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          build-essential \
          libssl-dev \
          pkg-config \
          libpq5 \
          libpq-dev \
          clang \
          cmake \
          gcc-aarch64-linux-gnu
       
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
      
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      
      - name: Build Gateway project
        run: cargo build --release --target ${{ matrix.target }} --bin ai-gateway
          
      - name: Upload AI Gateway artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-gateway-linux-${{ matrix.target == 'aarch64-unknown-linux-gnu' && 'aarch64' || 'x86_64' }}
          path: target/${{ matrix.target }}/release/ai-gateway
          retention-days: 30

  build-macos:
    name: Build for macOS
    timeout-minutes: 60
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          brew install postgresql sqlite3
       
      - name: Set library paths
        run: |
          echo "LIBRARY_PATH=$(brew --prefix)/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "CPATH=$(brew --prefix)/include:$CPATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
       
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
      
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      
      - name: Build Gateway project
        env:
          PQ_LIB_STATIC: "1"
        run: cargo build --release --target ${{ matrix.target }} --bin ai-gateway
          
      - name: Upload AI Gateway artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-gateway-macos-${{ matrix.target == 'aarch64-apple-darwin' && 'aarch64' || 'x86_64' }}
          path: target/${{ matrix.target }}/release/ai-gateway
          retention-days: 30

  create-release:
    name: Create Release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Prepare release binaries
        run: |
          mkdir -p release
          cp artifacts/ai-gateway-linux-x86_64/ai-gateway release/ai-gateway-linux-x86_64
          cp artifacts/ai-gateway-linux-aarch64/ai-gateway release/ai-gateway-linux-aarch64
          cp artifacts/ai-gateway-macos-x86_64/ai-gateway release/ai-gateway-macos-x86_64
          cp artifacts/ai-gateway-macos-aarch64/ai-gateway release/ai-gateway-macos-aarch64
          chmod +x release/*
          ls -lh release/
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ contains(github.ref_name, '-prerelease') && format('Prerelease {0}', github.ref_name) || format('Release {0}', github.ref_name) }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-prerelease') }}
          generate_release_notes: true
          files: |
            release/ai-gateway-linux-x86_64
            release/ai-gateway-linux-aarch64
            release/ai-gateway-macos-x86_64
            release/ai-gateway-macos-aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-formula:
    name: Update Homebrew Formula
    needs: [create-release]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Download release assets
        run: |
          mkdir -p release-assets
          # Download all release assets
          gh release download ${{ github.ref_name }} --dir release-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update formula.rb using Ruby script
        run: |
          # Make the script executable
          chmod +x scripts/update-formula.rb
          
          # Run the script with all available assets
          ruby scripts/update-formula.rb ${{ github.ref_name }} \
            release-assets/ai-gateway-linux-x86_64 \
            release-assets/ai-gateway-linux-aarch64 \
            release-assets/ai-gateway-macos-x86_64 \
            release-assets/ai-gateway-macos-aarch64

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/ellora.rb
          git diff --staged
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update formula.rb for ${{ github.ref_name }}"
            git push
          fi
            
