name: Build AI Gateway

on:
  push:
    branches:
      - main
      - feat/oss-refactor

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: main
  cancel-in-progress: true
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  build-linux:
    name: Build for Linux
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          build-essential \
          libssl-dev \
          pkg-config \
          libpq5 \
          libpq-dev \
          clang \
          cmake
       
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      
      - uses: Swatinem/rust-cache@v2
        with:
          key: linux-x86_64
      
      - name: Build Gateway project
        run: cargo build --release --bin ai-gateway
          
      - name: Upload AI Gateway artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-gateway-linux-x86_64
          path: target/release/ai-gateway
          retention-days: 30

  build-macos:
    name: Build for macOS
    timeout-minutes: 60
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - uses: actions/checkout@v3
       
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
      
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}
      
      - name: Build Gateway project
        run: cargo build --release --target ${{ matrix.target }} --bin ai-gateway
          
      - name: Upload AI Gateway artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai-gateway-macos-${{ matrix.target == 'aarch64-apple-darwin' && 'aarch64' || 'x86_64' }}
          path: target/${{ matrix.target }}/release/ai-gateway
          retention-days: 30
            
