name: Build AI Gateway

on:
  push:
    branches:
      - main
      - feat/oss-refactor

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: main
  cancel-in-progress: true
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          build-essential \
          libssl-dev \
          pkg-config \
          libpq5 \
          libpq-dev \
          clang \
          cmake
       
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-apple-darwin
      
      # - name: Add Apple Silicon target
      #   run: rustup target add aarch64-apple-darwin
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      
      - name: Install cargo-zigbuild
        run: cargo install cargo-zigbuild
      
      # - name: Build Gateway project (Linux)
      #   run: |
      #     cargo build --release
          
      # - name: Build Gateway project (macOS Intel)
      #   run: |
      #     cargo zigbuild --release --target x86_64-apple-darwin
          
      - name: Build Gateway project (macOS Apple Silicon)
        run: |
          cargo zigbuild --release --target aarch64-apple-darwin
          
      # - name: Upload AI Gateway artifact (Linux)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ai-gateway-linux-x86_64
      #     path: target/release/ai-gateway
      #     retention-days: 30
          
      # - name: Upload AI Gateway artifact (macOS Intel)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ai-gateway-macos-x86_64
      #     path: target/x86_64-apple-darwin/release/ai-gateway
      #     retention-days: 30
          
      - name: Upload AI Gateway artifact (macOS Apple Silicon)
        uses: actions/upload-artifact@v4
        with:
          name: ai-gateway-macos-aarch64
          path: target/aarch64-apple-darwin/release/ai-gateway
          retention-days: 30
            
